config/routes.rb
Deisgner::Application.routes.draw do
  get "admin" => 'admin#index'

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :deisgns do
  	resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :deisgn
end

app/models/deisgn.rb
class Deisgn < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize
  
  protected
  
  def authorize
    unless User.find_by_id(session[:user_id])
      redirect_to login_url, notice: "Please log in"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@deisgn = Deisgn.find(params[:deisgn_id])
		@comment = @deisgn.comments.create(params[:comment])
		redirect_to deisgn_path(@deisgn)
	end
end

app/controllers/deisgns_controller.rb
class DeisgnsController < ApplicationController
  # GET /deisgns
  # GET /deisgns.json
  def index
    @deisgns = Deisgn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @deisgns }
    end
  end

  # GET /deisgns/1
  # GET /deisgns/1.json
  def show
    @deisgn = Deisgn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @deisgn }
    end
  end

  # GET /deisgns/new
  # GET /deisgns/new.json
  def new
    @deisgn = Deisgn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @deisgn }
    end
  end

  # GET /deisgns/1/edit
  def edit
    @deisgn = Deisgn.find(params[:id])
  end

  # POST /deisgns
  # POST /deisgns.json
  def create
    @deisgn = Deisgn.new(params[:deisgn])

    respond_to do |format|
      if @deisgn.save
        format.html { redirect_to @deisgn, :notice => 'Deisgn was successfully created.' }
        format.json { render :json => @deisgn, :status => :created, :location => @deisgn }
      else
        format.html { render :action => "new" }
        format.json { render :json => @deisgn.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deisgns/1
  # PUT /deisgns/1.json
  def update
    @deisgn = Deisgn.find(params[:id])

    respond_to do |format|
      if @deisgn.update_attributes(params[:deisgn])
        format.html { redirect_to @deisgn, :notice => 'Deisgn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @deisgn.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deisgns/1
  # DELETE /deisgns/1.json
  def destroy
    @deisgn = Deisgn.find(params[:id])
    @deisgn.destroy

    respond_to do |format|
      format.html { redirect_to deisgns_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Ivalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/deisgns_helper.rb
module DeisgnsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome, superadmin</h1>
<p>We have TODO deisngs</p>

app/views/deisgns/_form.html.erb
<%= form_for(@deisgn) do |f| %>
  <% if @deisgn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deisgn.errors.count, "error") %> prohibited this deisgn from being saved:</h2>

      <ul>
      <% @deisgn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deisgns/edit.html.erb
<h1>Editing deisgn</h1>

<%= render 'form' %>

<%= link_to 'Show', @deisgn %> |
<%= link_to 'Back', deisgns_path %>

app/views/deisgns/index.html.erb
<h1>Listing deisgns</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deisgns.each do |deisgn| %>
  <tr>
    <td><%= deisgn.title %></td>
    <td><%= deisgn.url %></td>
    <td><%= deisgn.notes %></td>
    <td><%= link_to 'Show', deisgn %></td>
    <td><%= link_to 'Edit', edit_deisgn_path(deisgn) %></td>
    <td><%= link_to 'Destroy', deisgn, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deisgn', new_deisgn_path %>

app/views/deisgns/new.html.erb
<h1>New deisgn</h1>

<%= render 'form' %>

<%= link_to 'Back', deisgns_path %>

app/views/deisgns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @deisgn.title %>
</p>

<p>
  <b>Url:</b>
  <%= @deisgn.url %>
</p>

<p>
  <b>Notes:</b>
  <%= @deisgn.notes %>
</p>

<p>
	<h2>Shit people say about this deisgn</h2>
	<ul>
		<% @deisgn.comments.each do |comment| %>
		<li>
			<h3><a href="mailto:<%= comment.email %>"><%= comment.commenter %></a></h3>
			<a href="http://<%= comment.url %>"><%= comment.url %></a>
			
			<p><%= comment.body %></p>
		</li>
		<% end %>
	</ul>
</p>

<h2>Say some shit yourself</h2>

<div>
	<%= form_for([@deisgn, @deisgn.comments.build]) do |f| %>
		<div>
			<%= f.label :commenter %>
			<%= f.text_field :commenter %>
		</div>
		<div>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div>
			<%= f.label :url %>
			<%= f.text_field :url %>
		</div>
		<div>
			<%= f.label :body %>
			<%= f.text_area :body %>
		</div>
		<div>
			<%= f.submit %>
		</div>
	<% end %>
</div>

<%= link_to 'Edit', edit_deisgn_path(@deisgn) %> |
<%= link_to 'Back', deisgns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deisgner</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div style="float: left">
		<%= link_to "Users", users_path %> | 
		<%= link_to "Admin", admin_path %> | 
		<%= link_to "Deisgns", deisgns_path %> | 
	</div>
	<div style="float: right">
		<% unless session[:user_id] %>
			<%= link_to "Login", login_path %> | 
		<% else %>
			<%= link_to "Logout", logout_path, method: :delete %> | 
		<% end %>
	</div>
	<div style="clear: both;">&nbsp;</div>
	<hr />

	<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>